from: approve-config/application/application-dev.yml11
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456
#    virtual-host: /work-office
  sleuth:
    sampler:
      percentage: 1	#spans的收集率
eureka:
  instance:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"


